;;; ocamlformat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from ocamlformat.el

(autoload 'ocamlformat-before-save "ocamlformat" "\
Add this to .emacs to run ocamlformat on the current buffer when saving:

(add-hook \\='before-save-hook \\='ocamlformat-before-save)." t)
(register-definition-prefixes "ocamlformat" '("ocamlformat"))

;;; End of scraped data

(provide 'ocamlformat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ocamlformat-autoloads.el ends here
