;;; combobulate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from combobulate.el

(autoload 'combobulate-mode "combobulate" "\
Navigate and edit text by syntactic constructs

\\{combobulate-key-map}

This is a minor mode.  If called interactively, toggle the `Combobulate
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `combobulate-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "combobulate" '("combobulate-"))


;;; Generated autoloads from combobulate-contrib.el

(register-definition-prefixes "combobulate-contrib" '("combobulate-"))


;;; Generated autoloads from combobulate-css.el

(register-definition-prefixes "combobulate-css" '("combobulate-css-"))


;;; Generated autoloads from combobulate-debug.el

(register-definition-prefixes "combobulate-debug" '("combobulate--"))


;;; Generated autoloads from combobulate-display.el

(register-definition-prefixes "combobulate-display" '("combobulate-"))


;;; Generated autoloads from combobulate-envelope.el

(register-definition-prefixes "combobulate-envelope" '("combobulate-"))


;;; Generated autoloads from combobulate-html.el

(register-definition-prefixes "combobulate-html" '("combobulate-"))


;;; Generated autoloads from combobulate-interface.el

(register-definition-prefixes "combobulate-interface" '("combobulate-" "lambda-slots"))


;;; Generated autoloads from combobulate-js-ts.el

(register-definition-prefixes "combobulate-js-ts" '("combobulate-j"))


;;; Generated autoloads from combobulate-json.el

(register-definition-prefixes "combobulate-json" '("combobulate-json-"))


;;; Generated autoloads from combobulate-manipulation.el

(register-definition-prefixes "combobulate-manipulation" '("combobulate-"))


;;; Generated autoloads from combobulate-misc.el

(register-definition-prefixes "combobulate-misc" '("combobulate-"))


;;; Generated autoloads from combobulate-navigation.el

(register-definition-prefixes "combobulate-navigation" '("combobulate-" "with-argument-repetition"))


;;; Generated autoloads from combobulate-procedure.el

(register-definition-prefixes "combobulate-procedure" '("combobulate-pro"))


;;; Generated autoloads from combobulate-python.el

(register-definition-prefixes "combobulate-python" '("combobulate-p"))


;;; Generated autoloads from combobulate-query.el

(autoload 'combobulate-query-builder "combobulate-query" "\
Open an interactive query builder buffer.

Design and test tree-sitter queries interactively with syntax
highlighting and node completion." t)
(register-definition-prefixes "combobulate-query" '("combobulate-"))


;;; Generated autoloads from combobulate-rules.el

(register-definition-prefixes "combobulate-rules" '("combobulate-rules-"))


;;; Generated autoloads from combobulate-settings.el

(register-definition-prefixes "combobulate-settings" '("combobulate-"))


;;; Generated autoloads from combobulate-yaml.el

(register-definition-prefixes "combobulate-yaml" '("combobulate-yaml-setup"))


;;; Generated autoloads from combobulate-ztree.el

(register-definition-prefixes "combobulate-ztree" '("combobulate-ztree-"))

;;; End of scraped data

(provide 'combobulate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; combobulate-autoloads.el ends here
